In [ ]:
# Experiment 5: Implementation of K-Nearest Neighbours (K-NN)
# Aim: Implement K-Nearest Neighbours algorithm in Python
#      and classify samples using the Iris dataset.

# Import required libraries
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report


# ---------------------------------------------------------
# STEP 1: Load the Iris dataset
# ---------------------------------------------------------

iris = load_iris()

X = iris.data
y = iris.target

print("Iris Dataset")
print("------------")

print("Features:")
print(iris.feature_names)

print("\nTarget Classes:")
print(iris.target_names)

print("\nFirst 5 samples:")
print(X[:5])


# ---------------------------------------------------------
# STEP 2: Split the dataset into training and testing data
# ---------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nNumber of training samples:", len(X_train))
print("Number of testing samples:", len(X_test))


# ---------------------------------------------------------
# STEP 3: Create the K-NN classifier
# ---------------------------------------------------------

# K = 5
k = 5

knn = KNeighborsClassifier(n_neighbors=k)


# ---------------------------------------------------------
# STEP 4: Train the K-NN model
# ---------------------------------------------------------

knn.fit(X_train, y_train)


# ---------------------------------------------------------
# STEP 5: Predict the test samples
# ---------------------------------------------------------

y_pred = knn.predict(X_test)


# ---------------------------------------------------------
# STEP 6: Calculate accuracy
# ---------------------------------------------------------

accuracy = accuracy_score(y_test, y_pred)

print("\n" + "=" * 50)
print("K-NEAREST NEIGHBOURS RESULTS")
print("=" * 50)

print("\nK value:", k)

print("Accuracy:", round(accuracy * 100, 2), "%")


# ---------------------------------------------------------
# STEP 7: Display actual and predicted values
# ---------------------------------------------------------

print("\nActual vs Predicted:")

for actual, predicted in zip(y_test, y_pred):
    print(
        "Actual:",
        iris.target_names[actual],
        "\tPredicted:",
        iris.target_names[predicted]
    )


# ---------------------------------------------------------
# STEP 8: Classification report
# ---------------------------------------------------------

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=iris.target_names
    )
)


# ---------------------------------------------------------
# STEP 9: Classify a new sample
# ---------------------------------------------------------

new_sample = np.array([
    [5.1, 3.5, 1.4, 0.2]
])

prediction = knn.predict(new_sample)

print("\nNew Sample:")
print(new_sample)

print("\nPredicted Class:")
print(iris.target_names[prediction[0]])

Iris Dataset
------------
Features:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target Classes:
['setosa' 'versicolor' 'virginica']

First 5 samples:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Number of training samples: 120
Number of testing samples: 30

K-NEAREST NEIGHBOURS RESULTS

K value: 5
Accuracy: 100.0 %

Actual vs Predicted:
Actual: versicolor 	Predicted: versicolor
Actual: setosa 	Predicted: setosa
Actual: virginica 	Predicted: virginica
Actual: versicolor 	Predicted: versicolor
Actual: versicolor 	Predicted: versicolor
Actual: setosa 	Predicted: setosa
Actual: versicolor 	Predicted: versicolor
Actual: virginica 	Predicted: virginica
Actual: versicolor 	Predicted: versicolor
Actual: versicolor 	Predicted: versicolor
Actual: virginica 	Predicted: virginica
Actual: setosa 	Predicted: setosa
Actual: setosa 	Predicted: setosa
Actual: setosa 	Predicted: setosa
Actual: setosa 	Predicted: 